title: School Course Catalog
school_name: SICTC
description: A showcase of our amazing academic programs.
baseurl: "" # Leave empty if your site is at username.github.io
collections:
  courses:
    output: true
defaults:
  - scope:
      type: course
    values:
      layout: course
  - scope:
      type: teacher
    values:
      layout: teacher
  - scope:
      type: classroom
    values:
      layout: classroom