title: School Course Catalog
school_name: SICTC
description: A showcase of our amazing academic programs.
baseurl: "" # Leave empty if your site is at username.github.io
collections:
  course:
    permalink: "/:collection/:course_id/"
    output: true
  teacher:
    permalink: "/:collection/:course_id/"
    output: true
  classroom:
    permalink: "/:collection/:course_id/"
    output: true
defaults:
  - scope:
    path: course
    type: posts
    values:
      layout: course
  - scope:
    path: teacher
    type: posts
    values:
      layout: teacher
  - scope:
    path: classroom
    type: posts
    values:
      layout: classroom