# these values are available in layouts with {{ site.whatever }}
title: School Course Catalog
school_name: SICTC
description: SICTC Virtual Open House Website
baseurl: "" # Leave empty if your site is at username.github.io
collections:
  courses:
    output: true