name: Deploy Jekyll

on:
  ## uncomment to make automatic
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Deploy to Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site # Jekyll output folder
          branch: gh-pages # Target branch for compiled site
